### ISSUE TITLE
Link to geo_location.html is 404

### ISSUE THREAD

**Issue by rpvnwnkl** [tuftsdev/WebProgramming#4]
Hi Ming,

The last link on this page: https://tuftsdev.github.io/WebProgramming/notes/event_handling.html

leads to a 404. Here is the link: https://tuftsdev.github.io/WebProgramming/examples/geolocation/geo_example.html

I wasn't able to find a geolocation folder in the examples folder in this repo.

Interested in taking a peak, if it's available. Any ideas?

**Comment by mchow01** [comment]
Fixed last fall, https://tuftsdev.github.io/WebProgramming/examples/google_maps/whereami.html
